name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
  
      #- name: set image tag frontend
      #id: tag
      #run : echo "::set-output name=image_tag::hrk123123/frontend:$(date +%s)"

    - name: install ssh client
      run: sudo apt-get install openssh-client -y

    - name: configure ssh key
      run: echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && cat ~/.ssh/id_rsa

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@13.232.235.143 'bash -s' < mkdir /tmp/tmp1
      

