name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      env:
        image_tag: "hrk123123/frontend:$(date +%s)"
    - name: Build the Docker image
      run: cd frontend && docker build . -t $image_tag

    - name: login into docker hub 
      run: echo "${{ secrets.DOCKER_HUB_CICD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: push image to docker hub
      run: docker push $image_tag
